"""
src/agents/advisory.py
======================
Consultant Agent — Executive Advisory.

Consolidates Agent 1 (diagnosis), Agent 2 (frameworks) and Agent 3 (scores)
into a structured advisory brief:

* Executive summary
* Key risk findings (top shipments / routes)
* Immediate actions (next 0-30 days)
* Long-term strategies (quarter+)
* Framework basis (citations for traceability)

Narrative generation uses Ollama (``OLLAMA_LLM_MODEL``) when available; a
deterministic, rule-based generator is used otherwise so output is always
produced and tests are reproducible.
"""
from __future__ import annotations

from dataclasses import dataclass, field

import pandas as pd

from config import OLLAMA_HOST, OLLAMA_LLM_MODEL
from src.agents.framework_retrieval import Retrieved
from src.agents.nlp_diagnosis import DiagnosisResult
from src.agents.risk_scoring import ScoringResult
from src.utils.logging_config import get_logger

log = get_logger(__name__)


@dataclass
class AdvisoryBrief:
    executive_summary: str = ""
    key_findings: list[str] = field(default_factory=list)
    immediate_actions: list[str] = field(default_factory=list)
    long_term_strategies: list[str] = field(default_factory=list)
    framework_basis: list[str] = field(default_factory=list)
    generated_by: str = "template"  # or "ollama"

    def to_markdown(self) -> str:
        def bullets(items: list[str]) -> str:
            return "\n".join(f"- {i}" for i in items) if items else "- (none)"
        return (
            f"# Executive Risk Advisory — Logistics\n\n"
            f"_Generated by: {self.generated_by}_\n\n"
            f"## Executive Summary\n{self.executive_summary}\n\n"
            f"## Key Findings\n{bullets(self.key_findings)}\n\n"
            f"## Immediate Actions (0–30 days)\n{bullets(self.immediate_actions)}\n\n"
            f"## Long-Term Strategies\n{bullets(self.long_term_strategies)}\n\n"
            f"## Framework Basis\n{bullets(self.framework_basis)}\n"
        )


# ── action libraries keyed by theme ───────────────────────────────────────
_IMMEDIATE = {
    "delay": "Reroute affected shipments around congested lanes and notify "
             "customers proactively with revised ETAs.",
    "fuel_spike": "Trigger fuel-surcharge clauses and review the most fuel-"
                  "intensive routes for immediate load/route optimisation.",
    "staff_shortage": "Activate the contingent-labour pool and reallocate crew "
                      "to the highest-throughput nodes.",
    "complaints": "Stand up a complaint triage cell and issue proactive "
                  "service-recovery communications to affected accounts.",
    "weather": "Invoke weather-trigger playbooks; pre-position buffer capacity "
               "on at-risk lanes.",
    "geopolitical": "Validate alternative lanes and confirm compliance for any "
                    "newly affected corridors.",
    "port": "Coordinate with port authorities on berth scheduling and shift "
            "volume to alternative terminals where feasible.",
}
_LONGTERM = {
    "delay": "Build lead-time buffers and pre-negotiate alternative carriers to "
             "reduce schedule variance.",
    "fuel_spike": "Implement a structured fuel-hedging programme for predictable "
                  "volumes and index surcharges to a public benchmark.",
    "staff_shortage": "Invest in cross-training and selective automation to lower "
                      "the headcount-to-volume ratio.",
    "complaints": "Establish SLAs with closed-loop root-cause corrective action "
                  "to protect reputation and reduce churn.",
    "geopolitical": "Diversify across multiple ports/suppliers to reduce single-"
                    "node concentration risk.",
    "port": "Pursue multi-port diversification and regionalised capacity.",
}


def _heuristic_brief(diag: DiagnosisResult, scoring: ScoringResult,
                     frameworks: list[Retrieved]) -> AdvisoryBrief:
    df = scoring.df
    p = scoring.portfolio
    quad = scoring.quadrant_counts
    brief = AdvisoryBrief(generated_by="template")

    # Executive summary
    n = len(df)
    improve = quad.get("Improve", 0)
    brief.executive_summary = (
        f"Across {n} shipments the portfolio shows a composite risk of "
        f"{p.get('composite', 0):.2f}/5 (financial {p.get('financial', 0):.1f}, "
        f"operational {p.get('operational', 0):.1f}, reputational "
        f"{p.get('reputational', 0):.1f}). {improve} shipment(s) fall in the "
        f"high-probability / high-impact 'Improve' quadrant and require priority "
        f"intervention. Dominant themes: "
        f"{', '.join(sorted(diag.theme_counts, key=diag.theme_counts.get, reverse=True)[:3]) or 'none'}."
    )

    # Key findings — worst shipments + worst route
    top = df.sort_values("composite_score", ascending=False).head(3)
    for _, r in top.iterrows():
        brief.key_findings.append(
            f"Shipment {r.get('ShipmentID', '?')} on {r.get('Route', '?')}: "
            f"composite {r['composite_score']:.2f} ({r['quadrant']}), "
            f"delay {float(r.get('Delay', 0)):.0f}h, "
            f"complaints {int(r.get('Complaints', 0))}."
        )
    if "Route" in df.columns:
        worst_route = (
            df.groupby("Route")["composite_score"].mean().sort_values(ascending=False)
        )
        if len(worst_route):
            brief.key_findings.append(
                f"Highest-risk lane: '{worst_route.index[0]}' "
                f"(avg composite {worst_route.iloc[0]:.2f})."
            )

    # Actions from dominant themes
    themes_sorted = sorted(diag.theme_counts, key=diag.theme_counts.get, reverse=True)
    for th in themes_sorted:
        if th in _IMMEDIATE and _IMMEDIATE[th] not in brief.immediate_actions:
            brief.immediate_actions.append(_IMMEDIATE[th])
        if th in _LONGTERM and _LONGTERM[th] not in brief.long_term_strategies:
            brief.long_term_strategies.append(_LONGTERM[th])
    # Structural strategy if route concentration was flagged
    for c in diag.constraints:
        if "concentration" in c:
            brief.long_term_strategies.append(
                "Reduce route concentration via multi-port / multi-carrier "
                "diversification and network stress-testing."
            )
    if not brief.immediate_actions:
        brief.immediate_actions.append(
            "Maintain monitoring; no acute themes detected this period."
        )
    if not brief.long_term_strategies:
        brief.long_term_strategies.append(
            "Continue resilience baseline: buffers, supplier diversity, horizon scanning."
        )

    brief.framework_basis = [f"{f.source}" for f in frameworks]
    return brief


def _ollama_brief(diag: DiagnosisResult, scoring: ScoringResult,
                  frameworks: list[Retrieved]) -> AdvisoryBrief | None:
    """Try to enrich the executive summary with a local LLM. Returns None on failure."""
    try:
        import ollama
        client = ollama.Client(host=OLLAMA_HOST)
    except Exception as exc:
        log.info("Ollama LLM unavailable (%s).", type(exc).__name__)
        return None

    base = _heuristic_brief(diag, scoring, frameworks)
    context = (
        f"Portfolio scores: {scoring.portfolio}. "
        f"Quadrants: {scoring.quadrant_counts}. "
        f"Themes: {diag.theme_counts}. "
        f"Constraints: {diag.constraints}. "
        f"Frameworks: {[f.source for f in frameworks]}."
    )
    prompt = (
        "You are a logistics risk consultant. Write a concise, board-ready "
        "executive summary (max 6 sentences) based strictly on this analysis. "
        "Be specific and actionable; do not invent numbers.\n\n" + context
    )
    try:
        resp = client.chat(model=OLLAMA_LLM_MODEL,
                           messages=[{"role": "user", "content": prompt}])
        text = resp["message"]["content"].strip()
        if text:
            base.executive_summary = text
            base.generated_by = f"ollama:{OLLAMA_LLM_MODEL}"
            log.info("Advisory summary generated by Ollama.")
        return base
    except Exception as exc:
        log.warning("Ollama generation failed (%s); using template.", exc)
        return None


def generate_advisory(diag: DiagnosisResult, scoring: ScoringResult,
                      frameworks: list[Retrieved],
                      use_llm: bool = True) -> AdvisoryBrief:
    """Produce the consolidated advisory brief (LLM-enriched if possible)."""
    if use_llm:
        brief = _ollama_brief(diag, scoring, frameworks)
        if brief is not None:
            return brief
    return _heuristic_brief(diag, scoring, frameworks)
